#是否开启缓存，开始是可设置为flase，默认是true
thymeleaf:
  prefix: classpath:/templates/  #prefix：指定模板所在的目录
  check-template-location: true  #check-tempate-location: 检查模板路径是否存在
  cache: false  #cache: 是否<dependencyManagement>
    <!--直接依赖parent 虽然方便，但是读者咋i公司中开u发微服务项目或者多模块项目是一般需要使用公司自己的parent,
    如果这个时间还行进行项目依赖版本的统一管理，就需要受用dependencymanagement-->
    <dependencies>
    <dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-dependencies</artifactId>
    <version>2.0.4.RELEASE</version>
    <type>pom</type>
    <scope>import</scope>
    </dependency>

    </dependencies>
    </dependencyManagement>缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
  suffix:  .html
  #encoding: UTF-8
  #content-type: text/html
  #mode: HTML5

server:
    context-path: /
    servlet-path: /
spring:
  servlet:
    multipart:
      enabled: true

